import os
import io
from pathlib import Path
from typing import List, Dict
from ..core.logging import logger


class EnhancedPDFExporter:
    """PDF exporter with support for AI notes and uploaded notes using xhtml2pdf."""

    def generate_ai_notes_pdf(
        self,
        video_id: str,
        video_title: str,
        video_url: str,
        summary: str,
        notes: str
    ) -> bytes:
        """Generate PDF for AI-generated notes (summary + detailed notes).
        
        Args:
            video_id: YouTube video ID
            video_title: Video title
            video_url: YouTube URL
            summary: AI-generated summary
            notes: AI-generated detailed notes (markdown)
            
        Returns:
            PDF file as bytes
        """
        # Convert markdown to HTML
        try:
            import markdown2
            notes_html = markdown2.markdown(notes, extras=["tables", "fenced-code-blocks"])
        except ImportError as e:
            logger.warning(f"markdown2 import failed: {e}, using plain text")
            # Simple fallback: replace newlines with <br>
            notes_html = notes.replace('\n', '<br>\n')

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                @page {{
                    size: A4;
                    margin: 2.5cm;
                }}
                body {{
                    font-family: 'Arial', 'Helvetica', sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                h1 {{
                    color: #1a1a1a;
                    font-size: 24px;
                    margin-bottom: 10px;
                    border-bottom: 3px solid #4CAF50;
                    padding-bottom: 10px;
                }}
                .metadata {{
                    color: #666;
                    font-size: 12px;
                    margin-bottom: 20px;
                }}
                .metadata a {{
                    color: #2196F3;
                    text-decoration: none;
                }}
                .section {{
                    margin-bottom: 25px;
                }}
                .section h2 {{
                    color: #2c3e50;
                    font-size: 18px;
                    margin-top: 20px;
                    margin-bottom: 12px;
                    border-left: 4px solid #4CAF50;
                    padding-left: 12px;
                }}
                .summary {{
                    background-color: #f8f9fa;
                    padding: 15px;
                    border-radius: 5px;
                    border-left: 4px solid #4CAF50;
                }}
                .notes-content {{
                    margin-top: 12px;
                }}
                .notes-content h3 {{
                    color: #34495e;
                    font-size: 16px;
                    margin-top: 15px;
                }}
                .notes-content ul, .notes-content ol {{
                    margin-left: 18px;
                }}
                .notes-content code {{
                    background-color: #f4f4f4;
                    padding: 2px 6px;
                    border-radius: 3px;
                    font-family: 'Courier New', monospace;
                    font-size: 13px;
                }}
                .notes-content pre {{
                    background-color: #f4f4f4;
                    padding: 10px;
                    border-radius: 4px;
                    overflow-x: auto;
                }}
                .footer {{
                    margin-top: 30px;
                    padding-top: 15px;
                    border-top: 1px solid #ddd;
                    color: #888;
                    font-size: 11px;
                    text-align: center;
                }}
            </style>
        </head>
        <body>
            <h1>{self._escape_html(video_title or video_id)}</h1>
            <div class="metadata">
                <p><strong>Video:</strong> <a href="{self._escape_html(video_url)}">{self._escape_html(video_url)}</a></p>
                <p><strong>Video ID:</strong> {self._escape_html(video_id)}</p>
            </div>
            
            <div class="section">
                <h2>Summary</h2>
                <div class="summary">
                    <p>{self._escape_html(summary or 'No summary available.')}</p>
                </div>
            </div>
            
            <div class="section">
                <h2>Detailed Study Notes</h2>
                <div class="notes-content">
                    {notes_html or '<p>No detailed notes available.</p>'}
                </div>
            </div>
            
            <div class="footer">
                Generated by AskTube - AI-Powered Study Notes
            </div>
        </body>
        </html>
        """

        # Generate PDF using xhtml2pdf
        try:
            from xhtml2pdf import pisa
            result = io.BytesIO()
            pdf = pisa.pisaDocument(io.BytesIO(html_content.encode('utf-8')), result)
            
            if pdf.err:
                raise Exception(f"PDF generation had errors: {pdf.err}")
            
            return result.getvalue()
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise

    def generate_uploaded_notes_pdf(
        self,
        video_id: str,
        video_title: str,
        uploaded_files: List[Dict[str, str]]
    ) -> bytes:
        """Generate PDF for uploaded handwritten notes images using Pillow.
        
        Args:
            video_id: YouTube video ID
            video_title: Video title
            uploaded_files: List of dicts with 'filename' and 'path' keys
            
        Returns:
            PDF file as bytes
        """
        if not uploaded_files:
            raise ValueError("No uploaded files to generate PDF")

        try:
            from PIL import Image
            
            image_list = []
            for file_info in uploaded_files:
                file_path = file_info.get('path', '')
                
                # Convert to absolute path if needed
                if not os.path.isabs(file_path):
                    file_path = os.path.abspath(file_path)
                
                try:
                    # Open image and convert to RGB (required for PDF)
                    img = Image.open(file_path)
                    if img.mode != 'RGB':
                        img = img.convert('RGB')
                    image_list.append(img)
                except Exception as e:
                    logger.warning(f"Failed to process image {file_path}: {e}")
                    continue
            
            if not image_list:
                raise ValueError("No valid images found to convert")

            # Save to bytes buffer
            pdf_bytes = io.BytesIO()
            
            # Save the first image and append the rest
            image_list[0].save(
                pdf_bytes, 
                format='PDF', 
                save_all=True, 
                append_images=image_list[1:],
                resolution=100.0, 
                quality=95, 
                optimize=True
            )
            
            return pdf_bytes.getvalue()
            
        except Exception as e:
            logger.error(f"Uploaded notes PDF generation failed: {e}")
            raise

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters."""
        if not text:
            return ""
        return (text
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;")
                .replace("'", "&#39;"))
